//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringandReportingCOVID19.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_location
    {
        public int ID_EL { get; set; }
        public string Emp_id { get; set; }
        public Nullable<System.DateTime> Date_AddLocation { get; set; }
        public string Days_Isolation { get; set; }
        public string Current_position { get; set; }
        public string titik_kordinat { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
    }
}
