//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitoringandReportingCOVID19.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MRC19Entities : DbContext
    {
        public MRC19Entities()
            : base("name=MRC19Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Temp_Employee> Temp_Employee { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<V_ActiveCases> V_ActiveCases { get; set; }
        public virtual DbSet<V_DeathCases> V_DeathCases { get; set; }
        public virtual DbSet<V_RecoveryCases> V_RecoveryCases { get; set; }
        public virtual DbSet<V_ConfirmEMP> V_ConfirmEMP { get; set; }
        public virtual DbSet<V_CFgender> V_CFgender { get; set; }
        public virtual DbSet<V_CMgender> V_CMgender { get; set; }
        public virtual DbSet<CovidConfirmCas> CovidConfirmCases { get; set; }
        public virtual DbSet<V_BarChart> V_BarChart { get; set; }
        public virtual DbSet<V_EmpFemale> V_EmpFemale { get; set; }
        public virtual DbSet<V_EmpMale> V_EmpMale { get; set; }
        public virtual DbSet<V_Uploadnew> V_Uploadnew { get; set; }
        public virtual DbSet<V_Uploadold> V_Uploadold { get; set; }
        public virtual DbSet<AccountUser> AccountUsers { get; set; }
        public virtual DbSet<V_statuemp> V_statuemp { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee_location> Employee_location { get; set; }
    }
}
